// <auto-generated />
namespace smartHookah.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seat2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seat2));
        
        string IMigrationMetadata.Id
        {
            get { return "201708200947372_seat2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
