// <auto-generated />
namespace smartHookah.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class business_hours_not_mapped_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(business_hours_not_mapped_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281021144_business_hours_not_mapped_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
