// <auto-generated />
namespace smartHookah.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class person_refactor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(person_refactor));
        
        string IMigrationMetadata.Id
        {
            get { return "201811081621502_person_refactor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
