//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Order {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Order() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smartHookah.Resources.Order.Order", typeof(Order).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant choose ? Just write us your order.
        /// </summary>
        public static string cantChoose {
            get {
                return ResourceManager.GetString("cantChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current order is now.
        /// </summary>
        public static string currentOrderPrice {
            get {
                return ResourceManager.GetString("currentOrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add some extras.
        /// </summary>
        public static string dropExtra {
            get {
                return ResourceManager.GetString("dropExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us choose.
        /// </summary>
        public static string letusChoose {
            get {
                return ResourceManager.GetString("letusChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place menu.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your order.
        /// </summary>
        public static string orderConfirm {
            get {
                return ResourceManager.GetString("orderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        public static string orderDetails {
            get {
                return ResourceManager.GetString("orderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order price.
        /// </summary>
        public static string orderPrice {
            get {
                return ResourceManager.GetString("orderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string orderState {
            get {
                return ResourceManager.GetString("orderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order time.
        /// </summary>
        public static string orderTime {
            get {
                return ResourceManager.GetString("orderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order your hookah.
        /// </summary>
        public static string orderYourHookah {
            get {
                return ResourceManager.GetString("orderYourHookah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter table code.
        /// </summary>
        public static string pleaseEnterTableCode {
            get {
                return ResourceManager.GetString("pleaseEnterTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to order.
        /// </summary>
        public static string proceedToOrder {
            get {
                return ResourceManager.GetString("proceedToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random mix.
        /// </summary>
        public static string randomMix {
            get {
                return ResourceManager.GetString("randomMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table code.
        /// </summary>
        public static string seatCode {
            get {
                return ResourceManager.GetString("seatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat specify.
        /// </summary>
        public static string seatSpecify {
            get {
                return ResourceManager.GetString("seatSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select our prepared mixes:.
        /// </summary>
        public static string selectPreparedMixes {
            get {
                return ResourceManager.GetString("selectPreparedMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What bowl do you want?.
        /// </summary>
        public static string whatBowl {
            get {
                return ResourceManager.GetString("whatBowl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What hookah do you want?.
        /// </summary>
        public static string whatHookah {
            get {
                return ResourceManager.GetString("whatHookah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What tobacco do you want ( Up to 4 flavours) ?.
        /// </summary>
        public static string whatTobacco {
            get {
                return ResourceManager.GetString("whatTobacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your taste preferences.
        /// </summary>
        public static string yourTastePreferences {
            get {
                return ResourceManager.GetString("yourTastePreferences", resourceCulture);
            }
        }
    }
}
