//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smoke {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SmokeSession {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmokeSession() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smartHookah.Resources.SmokeSession.SmokeSession", typeof(SmokeSession).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string animation {
            get {
                return ResourceManager.GetString("animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowing.
        /// </summary>
        public static string blowing {
            get {
                return ResourceManager.GetString("blowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal.
        /// </summary>
        public static string coal {
            get {
                return ResourceManager.GetString("coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal count.
        /// </summary>
        public static string coalCount {
            get {
                return ResourceManager.GetString("coalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal type.
        /// </summary>
        public static string coalType {
            get {
                return ResourceManager.GetString("coalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit  information.
        /// </summary>
        public static string editSmokeSessionMetadata {
            get {
                return ResourceManager.GetString("editSmokeSessionMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End smoke session.
        /// </summary>
        public static string endSmokeSession {
            get {
                return ResourceManager.GetString("endSmokeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string gear {
            get {
                return ResourceManager.GetString("gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat manager.
        /// </summary>
        public static string heatManager {
            get {
                return ResourceManager.GetString("heatManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string live {
            get {
                return ResourceManager.GetString("live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My gear.
        /// </summary>
        public static string myGear {
            get {
                return ResourceManager.GetString("myGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My mixies.
        /// </summary>
        public static string myMixes {
            get {
                return ResourceManager.GetString("myMixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tobacco.
        /// </summary>
        public static string myTobacco {
            get {
                return ResourceManager.GetString("myTobacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No review.
        /// </summary>
        public static string noReview {
            get {
                return ResourceManager.GetString("noReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smoke sessions.
        /// </summary>
        public static string noSmokeSessions {
            get {
                return ResourceManager.GetString("noSmokeSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No smoking data.
        /// </summary>
        public static string noSmokingData {
            get {
                return ResourceManager.GetString("noSmokingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall rating.
        /// </summary>
        public static string overallRating {
            get {
                return ResourceManager.GetString("overallRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack &amp; Coals.
        /// </summary>
        public static string packAndCoals {
            get {
                return ResourceManager.GetString("packAndCoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack style.
        /// </summary>
        public static string packStyle {
            get {
                return ResourceManager.GetString("packStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string persons {
            get {
                return ResourceManager.GetString("persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your review.
        /// </summary>
        public static string pleaseWriteYourReview {
            get {
                return ResourceManager.GetString("pleaseWriteYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .
        /// </summary>
        public static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tobacco brand and flavor.
        /// </summary>
        public static string selectBrandAndFlavor {
            get {
                return ResourceManager.GetString("selectBrandAndFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Information.
        /// </summary>
        public static string sessionInformation {
            get {
                return ResourceManager.GetString("sessionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string showAll {
            get {
                return ResourceManager.GetString("showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke quality.
        /// </summary>
        public static string smokeQuality {
            get {
                return ResourceManager.GetString("smokeQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke sessions.
        /// </summary>
        public static string smokeSessions {
            get {
                return ResourceManager.GetString("smokeSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        public static string smoking {
            get {
                return ResourceManager.GetString("smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start smoking to see more.
        /// </summary>
        public static string startSmoking {
            get {
                return ResourceManager.GetString("startSmoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke data.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string tobaccoBrand {
            get {
                return ResourceManager.GetString("tobaccoBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavor.
        /// </summary>
        public static string tobaccoFlavor {
            get {
                return ResourceManager.GetString("tobaccoFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco quality.
        /// </summary>
        public static string tobaccoQuality {
            get {
                return ResourceManager.GetString("tobaccoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco taste.
        /// </summary>
        public static string tobaccoTaste {
            get {
                return ResourceManager.GetString("tobaccoTaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight(g).
        /// </summary>
        public static string tobaccoWeight {
            get {
                return ResourceManager.GetString("tobaccoWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-assign.
        /// </summary>
        public static string un_assign {
            get {
                return ResourceManager.GetString("un-assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write review.
        /// </summary>
        public static string writeReview {
            get {
                return ResourceManager.GetString("writeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write session review.
        /// </summary>
        public static string writeSessionReview {
            get {
                return ResourceManager.GetString("writeSessionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write review.
        /// </summary>
        public static string writeTobaccoReview {
            get {
                return ResourceManager.GetString("writeTobaccoReview", resourceCulture);
            }
        }
    }
}
