//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smartHookah.Resources.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowl.
        /// </summary>
        public static string bowl {
            get {
                return ResourceManager.GetString("bowl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowls.
        /// </summary>
        public static string bowls {
            get {
                return ResourceManager.GetString("bowls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more.
        /// </summary>
        public static string findMore {
            get {
                return ResourceManager.GetString("findMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to session.
        /// </summary>
        public static string goToSession {
            get {
                return ResourceManager.GetString("goToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homeSt {
            get {
                return ResourceManager.GetString("homeSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hookah.
        /// </summary>
        public static string hookah {
            get {
                return ResourceManager.GetString("hookah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hookahs.
        /// </summary>
        public static string hookahs {
            get {
                return ResourceManager.GetString("hookahs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in for more functions .
        /// </summary>
        public static string logInForMoreFunctions {
            get {
                return ResourceManager.GetString("logInForMoreFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string logOff {
            get {
                return ResourceManager.GetString("logOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixology.
        /// </summary>
        public static string mixology {
            get {
                return ResourceManager.GetString("mixology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My gear.
        /// </summary>
        public static string myGear {
            get {
                return ResourceManager.GetString("myGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter session code ( on stand display ) .
        /// </summary>
        public static string pleaseEnter {
            get {
                return ResourceManager.GetString("pleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session code.
        /// </summary>
        public static string sessionCode {
            get {
                return ResourceManager.GetString("sessionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All gear.
        /// </summary>
        public static string smokeEq {
            get {
                return ResourceManager.GetString("smokeEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stands.
        /// </summary>
        public static string stands {
            get {
                return ResourceManager.GetString("stands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My statistics.
        /// </summary>
        public static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco.
        /// </summary>
        public static string tobacco {
            get {
                return ResourceManager.GetString("tobacco", resourceCulture);
            }
        }
    }
}
