//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Person {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Person() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smartHookah.Resources.Person.Person", typeof(Person).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active orders.
        /// </summary>
        public static string activeOrders {
            get {
                return ResourceManager.GetString("activeOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active sessions.
        /// </summary>
        public static string activeSessions {
            get {
                return ResourceManager.GetString("activeSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begining of time.
        /// </summary>
        public static string begining {
            get {
                return ResourceManager.GetString("begining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to session.
        /// </summary>
        public static string goToSession {
            get {
                return ResourceManager.GetString("goToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        public static string last7Days {
            get {
                return ResourceManager.GetString("last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string moreInfo {
            get {
                return ResourceManager.GetString("moreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string places {
            get {
                return ResourceManager.GetString("places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puf count.
        /// </summary>
        public static string pufCount {
            get {
                return ResourceManager.GetString("pufCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session count.
        /// </summary>
        public static string sessionCount {
            get {
                return ResourceManager.GetString("sessionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session time.
        /// </summary>
        public static string sessionTime {
            get {
                return ResourceManager.GetString("sessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke overview.
        /// </summary>
        public static string smokeOverview {
            get {
                return ResourceManager.GetString("smokeOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke time.
        /// </summary>
        public static string smokeTime {
            get {
                return ResourceManager.GetString("smokeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string thisMonth {
            get {
                return ResourceManager.GetString("thisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        public static string thisYear {
            get {
                return ResourceManager.GetString("thisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
    }
}
